FROM amazoncorretto:11-alpine
ARG JAR_FILE=./build/libs/1m1s-server-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]

ENV SPRING_DATASOURCE_URL jdbc:mariadb://<컨테이너명>/<사용할 데이터베이스명>?useUnicode=true
ENV SPRING_DATASOURCE_USERNAME <사용할 데이터베이스 유저 이름>
ENV SPRING_DATASOURCE_PASSWORD <데이터베이스 유저 비밀번호>